export const videos = [
  {
    id: "v1",
    src: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    author: "@acme",
    caption: "POV: late-night coding session vibes ✨",
    likes: 1280,
    comments: 76,
    shares: 24,
    music: "lofi - smooth beats",
  },
  {
    id: "v2",
    src: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    author: "@wander",
    caption: "Lost in the city lights 🌃",
    likes: 842,
    comments: 58,
    shares: 19,
    music: "city pop - neon night",
  },
  {
    id: "v3",
    src: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    author: "@motion",
    caption: "Smooth transitions challenge 🎬",
    likes: 1563,
    comments: 132,
    shares: 61,
    music: "beat tape - glide",
  },
  {
    id: "v4",
    src: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    author: "@blender",
    caption: "Epic short film moments 🐉",
    likes: 2203,
    comments: 314,
    shares: 108,
    music: "cinematic - rise",
  },
];
